
version: 2
jobs:
  build:
    working_directory: ~/batch-9-Lumen
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout

      - run:  
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./cache/yarn
      - run:
          name: Client Tests
          command: |
            yarn test:client
      - run:
          name: Server tests
          command: |
            yarn test:server
      - add_ssh_keys:
          fingerprints:
            - $HEROKU_SSH_KEY
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "karan/heroku-server" ]; then
            git subtree push --prefix server git@heroku.com:$HEROKU_APP_NAME.git dev
            fi
